### ISSUE TITLE
teahhc garmbot about poop d4y

### ISSUE THREAD

**Issue by Hypaethral** [dnaf/Garmbot#38]

**Comment by k80w** [comment]
ur 2 focussd oin the wHENN of popp day 2 car abut thee WHT of poopp day; u dn  t undastnd that garmboy IS HMSELFL *POOPDAY**

**Comment by Hypaethral** [comment]
*whispers* holy shit

**Comment by bmccoy11** [comment]
this needs to be reopened, garmbot is unusable without knowing about poop d4y, please reopen and tag as critical

**Comment by k80w** [comment]
reopened, addng p00p day module as i speakj

**Comment by bmccoy11** [comment]
thanks v much b0io

**Comment by nimejia** [comment]
how2 activ8 poop cmd in the dicnord?

**Comment by bmccoy11** [comment]
💩:poop:
