### ISSUE TITLE
Add a !help command

### ISSUE THREAD

**Issue by nimejia** [dnaf/Garmbot#44]
add an actual help command that doesn't require you to click on a link. If you want I can type it up and pass it over to you.

**Comment by VanillaSixtySix** [comment]
Or perhaps have it DM you instead? Good idea.

**Comment by nimejia** [comment]
Yeah. Like I said, I can type it up.

**Comment by VanillaSixtySix** [comment]
Sure, you can do that. We'll take a look at it.

**Comment by nimejia** [comment]
**Fun**
!color [Color] Sets your color. If no color is specified, removes your color.
    e.g. !color green
!colors Lists the available colors on this server.
!tag Lists the tags on this server.
!tag [Name] Returns the specified tag.
    !tag test
!tag [Name] [Contents] Sets the tag to the specified contents.
    e.g. !tag test hello this is a test
**Moderation**
***NOTE:** Garmbot’s moderation tools are still a work-in-progress.*
!warn [User] [Reason] Warns the given user with the specified reason.
**Configuration**
!addcolor [Color] Adds the given roles to the list of self-assignable colors. Each role must be @mentionable when this command is run, but they don’t need to be mentionable after they are added.
    e.g. !addcolor @blue @red @green @yellow


Something like this?
